<?php

declare( strict_types = 1 );

namespace Automattic\WooCommerce\Internal\PushNotifications\Entities;

defined( 'ABSPATH' ) || exit;

<<<<<<< HEAD
use Automattic\WooCommerce\Internal\PushNotifications\Exceptions\PushTokenInvalidDataException;
use Automattic\WooCommerce\Internal\PushNotifications\Validators\PushTokenValidator;
=======
use InvalidArgumentException;
>>>>>>> origin/main

/**
 * Object representation of a push token.
 *
 * @since 10.4.0
 */
class PushToken {
	/**
	 * WordPress post type for storing push tokens.
	 */
	const POST_TYPE = 'wc_push_token';

	/**
<<<<<<< HEAD
	 * The locale to use for tokens when the locale is not set, e.g. for tokens
	 * created before `device_locale` was added.
	 */
	const DEFAULT_DEVICE_LOCALE = 'en_US';

	/**
=======
>>>>>>> origin/main
	 * Platform identifier for Apple devices.
	 */
	const PLATFORM_APPLE = 'apple';

	/**
	 * Platform identifier for Android devices.
	 */
	const PLATFORM_ANDROID = 'android';

	/**
	 * Platform identifier for web browsers.
	 */
	const PLATFORM_BROWSER = 'browser';

	/**
	 * Origin identifier for WooCommerce Android app.
	 */
	const ORIGIN_WOOCOMMERCE_ANDROID = 'com.woocommerce.android';

	/**
	 * Origin identifier for WooCommerce Android app development builds.
	 */
	const ORIGIN_WOOCOMMERCE_ANDROID_DEV = 'com.woocommerce.android:dev';

	/**
	 * Origin identifier for WooCommerce iOS app.
	 */
	const ORIGIN_WOOCOMMERCE_IOS = 'com.automattic.woocommerce';

	/**
	 * Origin identifier for WooCommerce iOS app development builds.
	 */
	const ORIGIN_WOOCOMMERCE_IOS_DEV = 'com.automattic.woocommerce:dev';

	/**
	 * Origin identifier for browsers.
	 */
	const ORIGIN_BROWSER = 'browser';

	/**
	 * List of valid platforms.
	 */
	const PLATFORMS = array(
		self::PLATFORM_APPLE,
		self::PLATFORM_ANDROID,
		self::PLATFORM_BROWSER,
	);

	/**
	 * List of valid origins.
	 */
	const ORIGINS = array(
		self::ORIGIN_BROWSER,
		self::ORIGIN_WOOCOMMERCE_ANDROID,
		self::ORIGIN_WOOCOMMERCE_ANDROID_DEV,
		self::ORIGIN_WOOCOMMERCE_IOS,
		self::ORIGIN_WOOCOMMERCE_IOS_DEV,
	);

	/**
<<<<<<< HEAD
	 * The ID of the token post.
=======
	 * Maximum length for push notification tokens.
	 */
	const MAX_TOKEN_LENGTH = 4096;

	/**
	 * The id of the token post.
>>>>>>> origin/main
	 *
	 * @var int|null
	 */
	private ?int $id = null;

	/**
<<<<<<< HEAD
	 * The ID of the user who owns the token.
=======
	 * The id of the user who owns the token.
>>>>>>> origin/main
	 *
	 * @var int|null
	 */
	private ?int $user_id = null;

	/**
	 * The token representing a device we can send a push notification to.
	 *
	 * @var string|null
	 */
	private ?string $token = null;

	/**
	 * The UUID of the device that generated the token.
	 *
	 * @var string|null
	 */
	private ?string $device_uuid = null;

	/**
	 * The platform the token was generated by.
	 *
	 * @var string|null
	 */
	private ?string $platform = null;

	/**
	 * The origin the token belongs to.
	 *
	 * @var string|null
	 */
	private ?string $origin = null;

	/**
<<<<<<< HEAD
	 * The locale of the device the token belongs to.
	 *
	 * @var string|null
	 */
	private ?string $device_locale = null;

	/**
	 * An array of metadata for the token.
	 *
	 * @var array|null
	 */
	private ?array $metadata = null;

	/**
	 * Creates a new PushToken instance with the given data.
	 *
	 * @param array $data Optional array with keys: id, user_id, token, device_uuid, platform, origin.
	 * @throws PushTokenInvalidDataException If any of the provided values fail validation.
	 *
	 * @since 10.6.0
	 */
	public function __construct( array $data = array() ) {
		if ( array_key_exists( 'id', $data ) ) {
			$this->set_id( (int) $data['id'] );
		}

		if ( array_key_exists( 'user_id', $data ) ) {
			$this->set_user_id( (int) $data['user_id'] );
		}

		if ( array_key_exists( 'token', $data ) ) {
			$this->set_token( (string) $data['token'] );
		}

		if ( array_key_exists( 'device_uuid', $data ) ) {
			$this->set_device_uuid( (string) $data['device_uuid'] );
		}

		if ( array_key_exists( 'platform', $data ) ) {
			$this->set_platform( (string) $data['platform'] );
		}

		if ( array_key_exists( 'origin', $data ) ) {
			$this->set_origin( (string) $data['origin'] );
		}

		if ( array_key_exists( 'device_locale', $data ) ) {
			$this->set_device_locale( (string) $data['device_locale'] );
		}

		if ( array_key_exists( 'metadata', $data ) ) {
			$this->set_metadata( (array) $data['metadata'] );
		}
	}

	/**
	 * Validates and sets the ID.
	 *
	 * @param int $id The ID of the token post.
	 * @throws PushTokenInvalidDataException If ID is not valid.
=======
	 * Creates a new PushToken instance with the specified properties.
	 *
	 * This is a utility method that provides a one-liner to create an instance
	 * with all the data you want to specify upfront. Using this method doesn't
	 * imply that the instance obtained is valid, complete, or usable in all
	 * contexts - validity is still determined by the internal validation logic
	 * of the class.
	 *
	 * @param int|null    $id          The ID of the token post.
	 * @param int|null    $user_id     The ID of the user who owns the token.
	 * @param string|null $token       The token representing a device we can send a push notification to.
	 * @param string|null $device_uuid The UUID of the device that generated the token.
	 * @param string|null $platform    The platform the token was generated by.
	 * @param string|null $origin      The origin the token belongs to.
	 * @throws InvalidArgumentException If any of the provided values fail validation.
	 * @return PushToken
	 *
	 * @since 10.4.0
	 */
	public static function get_new_instance(
		?int $id = null,
		?int $user_id = null,
		?string $token = null,
		?string $device_uuid = null,
		?string $platform = null,
		?string $origin = null
	): PushToken {
		$instance = new self();

		if ( null !== $id ) {
			$instance->set_id( $id );
		}

		if ( null !== $user_id ) {
			$instance->set_user_id( $user_id );
		}

		if ( null !== $token ) {
			$instance->set_token( $token );
		}

		if ( null !== $device_uuid ) {
			$instance->set_device_uuid( $device_uuid );
		}

		if ( null !== $platform ) {
			$instance->set_platform( $platform );
		}

		if ( null !== $origin ) {
			$instance->set_origin( $origin );
		}

		return $instance;
	}

	/**
	 * Sets the ID.
	 *
	 * @param int $id The id of the token post.
	 * @throws InvalidArgumentException If ID is <= 0.
>>>>>>> origin/main
	 * @return void
	 *
	 * @since 10.4.0
	 */
	public function set_id( int $id ): void {
<<<<<<< HEAD
		$result = PushTokenValidator::validate( compact( 'id' ), array( 'id' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
=======
		if ( $id <= 0 ) {
			throw new InvalidArgumentException( 'ID must be a positive integer.' );
>>>>>>> origin/main
		}

		$this->id = $id;
	}

	/**
<<<<<<< HEAD
	 * Validates and sets the user ID.
	 *
	 * @param int $user_id The ID of the user who owns the token.
	 * @throws PushTokenInvalidDataException If user ID is not valid.
=======
	 * Sets the user ID.
	 *
	 * @param int $user_id The id of the user who owns the token.
	 * @throws InvalidArgumentException If ID is <= 0.
>>>>>>> origin/main
	 * @return void
	 *
	 * @since 10.4.0
	 */
	public function set_user_id( int $user_id ): void {
<<<<<<< HEAD
		$result = PushTokenValidator::validate( compact( 'user_id' ), array( 'user_id' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
=======
		if ( $user_id <= 0 ) {
			throw new InvalidArgumentException( 'User ID must be a positive integer.' );
>>>>>>> origin/main
		}

		$this->user_id = $user_id;
	}

	/**
<<<<<<< HEAD
	 * Validates and sets the token.
	 *
	 * @param string $token The token representing a device we can send a push notification to.
	 * @throws PushTokenInvalidDataException If token is not valid.
=======
	 * Sets the token.
	 *
	 * @param string $token The token representing a device we can send a push notification to.
	 * @throws InvalidArgumentException If token is empty or exceeds maximum length.
>>>>>>> origin/main
	 * @return void
	 *
	 * @since 10.4.0
	 */
	public function set_token( string $token ): void {
<<<<<<< HEAD
		$result = PushTokenValidator::validate( compact( 'token' ), array( 'token' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
		}

		$this->token = trim( $token );
	}

	/**
	 * Validates and sets the device UUID, normalize empty (non-null) values to null.
	 *
	 * @param string|null $device_uuid The UUID of the device that generated the token.
	 * @throws PushTokenInvalidDataException If device UUID is not valid.
=======
		$token = trim( $token );

		if ( '' === $token ) {
			throw new InvalidArgumentException( 'Token cannot be empty.' );
		}

		if ( strlen( $token ) > self::MAX_TOKEN_LENGTH ) {
			throw new InvalidArgumentException(
				// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
				sprintf( 'Token exceeds maximum length of %s.', self::MAX_TOKEN_LENGTH )
			);
		}

		$this->token = $token;
	}

	/**
	 * Sets the device UUID, normalize empty (non-null) values to null.
	 *
	 * @param string|null $device_uuid The UUID of the device that generated the token.
>>>>>>> origin/main
	 * @return void
	 *
	 * @since 10.4.0
	 */
	public function set_device_uuid( ?string $device_uuid ): void {
<<<<<<< HEAD
		$result = PushTokenValidator::validate( compact( 'device_uuid' ), array( 'device_uuid' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
		}

=======
>>>>>>> origin/main
		if ( null !== $device_uuid ) {
			$device_uuid = trim( $device_uuid );
		}

<<<<<<< HEAD
		$this->device_uuid = $device_uuid ? $device_uuid : null;
	}

	/**
	 * Validates and sets the device locale.
	 *
	 * @param string $device_locale The locale of the device the token belongs to.
	 * @throws PushTokenInvalidDataException If device locale is not valid.
	 * @return void
	 *
	 * @since 10.6.0
	 */
	public function set_device_locale( string $device_locale ): void {
		$result = PushTokenValidator::validate( compact( 'device_locale' ), array( 'device_locale' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
		}

		$this->device_locale = trim( $device_locale );
	}

	/**
	 * Validates and sets the platform.
	 *
	 * @param string $platform The platform the token was generated by.
	 * @throws PushTokenInvalidDataException If platform is not valid.
=======
		$this->device_uuid = ( '' === $device_uuid ) ? null : $device_uuid;
	}

	/**
	 * Sets the platform.
	 *
	 * @param string $platform The platform the token was generated by.
	 * @throws InvalidArgumentException If the platform is invalid.
>>>>>>> origin/main
	 * @return void
	 *
	 * @since 10.4.0
	 */
	public function set_platform( string $platform ): void {
<<<<<<< HEAD
		$result = PushTokenValidator::validate( compact( 'platform' ), array( 'platform' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
		}

		$this->platform = trim( $platform );
	}

	/**
	 * Validates and sets the origin.
	 *
	 * @param string $origin The origin of the token, e.g. the app it came from.
	 * @throws PushTokenInvalidDataException If origin is not valid.
=======
		if ( ! in_array( $platform, self::PLATFORMS, true ) ) {
			throw new InvalidArgumentException( 'Platform for PushToken is invalid.' );
		}

		$this->platform = $platform;
	}

	/**
	 * Sets the origin.
	 *
	 * @param string $origin The origin of the token, e.g. the app it came from.
	 * @throws InvalidArgumentException If the origin is invalid.
>>>>>>> origin/main
	 * @return void
	 *
	 * @since 10.4.0
	 */
	public function set_origin( string $origin ): void {
<<<<<<< HEAD
		$result = PushTokenValidator::validate( compact( 'origin' ), array( 'origin' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
		}

		$this->origin = trim( $origin );
	}

	/**
	 * Validates and sets the metadata.
	 *
	 * @param array $metadata An array of metadata for the token, e.g. the app version, device OS etc.
	 * @throws PushTokenInvalidDataException If metadata is not valid.
	 * @return void
	 *
	 * @since 10.6.0
	 */
	public function set_metadata( array $metadata ): void {
		$result = PushTokenValidator::validate( compact( 'metadata' ), array( 'metadata' ) );

		if ( is_wp_error( $result ) ) {
			// phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped
			throw new PushTokenInvalidDataException( $result->get_error_message() );
		}

		if ( ! empty( $metadata ) ) {
			$keys   = array_map( 'sanitize_key', array_keys( $metadata ) );
			$values = array_map( 'sanitize_text_field', array_values( $metadata ) );

			/**
			 * Typehint for PHPStan, as it can't infer the $keys and $values are
			 * the same length therefore array_combine won't return false.
			 *
			 * @var array<string, string> $metadata
			 */
			$metadata = array_combine( $keys, $values );
		}

		$this->metadata = $metadata;
=======
		if ( ! in_array( $origin, self::ORIGINS, true ) ) {
			throw new InvalidArgumentException( 'Origin for PushToken is invalid.' );
		}

		$this->origin = $origin;
>>>>>>> origin/main
	}

	/**
	 * Gets the ID.
	 *
	 * @return int|null
	 *
	 * @since 10.4.0
	 */
	public function get_id(): ?int {
		return $this->id;
	}

	/**
	 * Gets the user ID.
	 *
	 * @return int|null
	 *
	 * @since 10.4.0
	 */
	public function get_user_id(): ?int {
		return $this->user_id;
	}

	/**
	 * Gets the token.
	 *
	 * @return string|null
	 *
	 * @since 10.4.0
	 */
	public function get_token(): ?string {
		return $this->token;
	}

	/**
	 * Gets the device UUID.
	 *
	 * @return string|null
	 *
	 * @since 10.4.0
	 */
	public function get_device_uuid(): ?string {
		return $this->device_uuid;
	}

	/**
	 * Gets the platform.
	 *
	 * @return string|null
	 *
	 * @since 10.4.0
	 */
	public function get_platform(): ?string {
		return $this->platform;
	}

	/**
	 * Gets the origin.
	 *
	 * @return string|null
	 *
	 * @since 10.4.0
	 */
	public function get_origin(): ?string {
		return $this->origin;
	}

	/**
<<<<<<< HEAD
	 * Gets the device locale.
	 *
	 * @return string|null
	 *
	 * @since 10.6.0
	 */
	public function get_device_locale(): ?string {
		return $this->device_locale;
	}

	/**
	 * Gets the metadata.
	 *
	 * @return array|null
	 *
	 * @since 10.6.0
	 */
	public function get_metadata(): ?array {
		return $this->metadata;
	}

	/**
=======
>>>>>>> origin/main
	 * Determines whether this token can be created.
	 *
	 * @return bool
	 *
	 * @since 10.4.0
	 */
	public function can_be_created(): bool {
		return ! $this->get_id() && $this->has_required_parameters();
	}

	/**
	 * Determines whether this token can be updated.
	 *
	 * @return bool
	 *
	 * @since 10.4.0
	 */
	public function can_be_updated(): bool {
		return $this->get_id() && $this->has_required_parameters();
	}

	/**
	 * Determines whether this token can be read.
	 *
	 * @return bool
	 *
	 * @since 10.4.0
	 */
	public function can_be_read(): bool {
		return (bool) $this->get_id();
	}

	/**
	 * Determines whether this token can be deleted.
	 *
	 * @return bool
	 *
	 * @since 10.4.0
	 */
	public function can_be_deleted(): bool {
		return (bool) $this->get_id();
	}

	/**
	 * Determines whether all the required non-ID parameters are filled.
	 *
	 * @return bool
	 *
	 * @since 10.4.0
	 */
	private function has_required_parameters(): bool {
		return $this->get_user_id()
			&& $this->get_token()
			&& $this->get_platform()
			&& $this->get_origin()
<<<<<<< HEAD
			&& $this->get_device_locale()
=======
>>>>>>> origin/main
			&& (
				$this->get_device_uuid()
				|| $this->get_platform() === self::PLATFORM_BROWSER
			);
	}
}
